from google import genai
from google.genai import types

from pathlib import Path
import csv
import os
from dotenv import load_dotenv
from exa_py import Exa


test = True

def spacer():
    print(f"\n\n---\n\n")

def zip_to_list(Zip):
    spacer()
    print(Zip)
    outer_list = []
    for items in Zip:
        spacer()
        print(items)
        inner_list= []
        for item in items:
            spacer()
            print(item)
            inner_list.append(item)
        outer_list.append(inner_list)
    return outer_list

# Gets the project directory: Avidex/
ROOT_DIR = Path(__file__).resolve().parent.parent.parent

# Defines the keys
GEMINI_KEY = os.getenv("GEMINI_KEY")
EXA_KEY = os.getenv("EXA_KEY")

# changes models
if test:
    MODEL="gemini-3.6-flash"
else:
    MODEL = "gemini-3.1-flash-lite"


# Loads the .env from Avidex/.env
load_dotenv( ROOT_DIR / ".env")
        

# A custom gemini function to parse out information from the existing, scraped info
parse_bird_info_function = {
    "type":"function",
    "name":"parse_info",
    "description":
    """Parse information about a bird given a text of info about it into a SQL PL call. An example entry data in the SQL table is:
    rarityID, commonName, species, callUrl, wingspan, size, identifyingMarks, range, description, photographUrl, matingSeason
    'Uncommon', 'Bald Eagle', 'Haliaeetus leucocephalus', 'https://baldeaglecallhere.com', 'The average Bald Eagle wingpsan is 6.9 feet', 'The average Bald Eagle is 27.9 inches to 37.8 inches long', 'The Bald Eagle is easily identified by its white capped head and neck, in contrast to the rest of its dark brown coat', 'Found all across North America, except for the most northern regions and below Mexico', 'The Bald Eagle got its name from the Middle English word, \'Balde\', meaning white-headed (not hairless!) These eagles mainly eat fish, and can be found around bodies of water. Though more often than not, they prefer to steal fish from other fishing animals, humans included.', 'https://baldeaglephotoshere.com', 'Bald Eagle nesting season typically begins in December, and lasts until July. Though their courtship behaviors may begin as early as late Fall, depending on location.
    
    Rarity can only be the options: Common, Legendary, Rare, Uncommon. callUrl and photographUrl must be NULL, and don't include birdID. description should be info inputted. Any info not included in the text should just be described as N/A. Each piece of information generated by you should have (Information Sourced with AI)"
    """,
    "parameters": {
        "type":"object",
        "properties": {
            "rarity": {"type":"string", "enum":["Common", "Uncommon", "Rare", "Legendary"]},
            "common_name": {"type":"string"},
            "species": {"type":"string"},
            "wingspan": {"type":"string", "nullable": True, "description":"null if not mentioned in the source text"},
            "size": {"type": "string", "nullable": True, "description": "null if not mentioned in the source text"},
            "identifying_marks": {"type": "string", "nullable": True, "description": "null if not mentioned in the source text"},
            "range": {"type": "string", "nullable": True, "description": "null if not mentioned in the source text"},
            "description": {"type": "string", "description": "The info submitted."},
            "mating_season": {"type": "string", "nullable": True, "description": "null if not mentioned in the source text"},
        },
    },
    "required": ["rarity", "common_name", "species", "wingspan", "size", "identifying_marks", "range", "description", "mating_season"],
}





def parse_bird_info(gemini_client,prompt):
    # Calling the parse_info function
    interaction = gemini_client.interactions.create(
        model=MODEL,
        input=prompt,
        tools=[{"type":"function", **parse_bird_info_function}]
    )

    # Taking that input and turning it into an ordered list
    for step in interaction.steps:
        if step.type == "function_call":
            args = step.arguments
            # Explicit key lookups sidestep random JSON ordering
            rarity = args["rarity"]
            common_name = args["common_name"]
            species = args["species"]
            wingspan = args["wingspan"]
            size = args["size"]
            identifying_marks = args["identifying_marks"]
            range_ = args["range"]
            description = args["description"]
            mating_season = args["mating_season"]

    # Turning this ordered list into a labeled list of lists size is [7][2]
    unprocessed_bird = [rarity, common_name, species, wingspan,size, identifying_marks, range_, description, mating_season]
    labels = ["rarity", "common_name", "species", "wingspan", "size", "identifying_marks", "range", "description", "mating_season"]
    labeled_unprocessed_bird = zip(labels,unprocessed_bird)
    labeled_unprocessed_bird = zip_to_list(labeled_unprocessed_bird)

    return labeled_unprocessed_bird





def exa_lookup_and_format(exa_client,bird_info):
    # Using Exa to look up the remaining missing information and validate the other remaining information.
    results = exa_client.search(
        query=f"{bird_info[2][1]}",
        type= "deep",
        system_prompt=f"""Lookup missing information and verify existing information about a bird given a list of info about it to prepare for a SQL PL entry. An example data entry created by a human in the SQL table is:
        rarityID, commonName, species, callUrl, wingspan, size, identifyingMarks, range, description, photographUrl, matingSeason
        'Uncommon', 'Bald Eagle', 'Haliaeetus leucocephalus', NULL, 'The average Bald Eagle wingpsan is 6.9 feet', 'The average Bald Eagle is 27.9 inches to 37.8 inches long', 'The Bald Eagle is easily identified by its white capped head and neck, in contrast to the rest of its dark brown coat', 'Found all across North America, except for the most northern regions and below Mexico', 'The Bald Eagle got its name from the Middle English word, \'Balde\', meaning white-headed (not hairless!) These eagles mainly eat fish, and can be found around bodies of water. Though more often than not, they prefer to steal fish from other fishing animals, humans included.', NULL, 'Bald Eagle nesting season typically begins in December, and lasts until July. Though their courtship behaviors may begin as early as late Fall, depending on location.
        
        The callUrl and photographUrl do not need to be looked up. Don't verify the existing information

        Check with multiple sources for validity.

        Add a tag describing the data after i.e. (verified) or (contradicted) following this legend:
        verified: reliable sources support the claim
        contradicted: reliable sources show it is false
        partially_correct: some details are right but others need correction
        disputed: credible sources disagree
        unverified: insufficient evidence
        needs_review: any result requiring a person's decision

        Prefer journals or scientific articles

        Existing info:
        {bird_info}
        """,
        output_schema= {
            "type":"object",
            "required": ["rarity","common_name","species","wingspan","size","identifying_marks", "range", "description", "mating_season"],
            "properties": {
                "rarity": {"type":"string", "enum":["Common", "Uncommon", "Rare", "Legendary"], "description":"Same as input data. Do not change or add tag"},
                "common_name": {"type":"string", "description":"Same as input data. Do not change or add tag"},
                "species": {"type":"string", "description":"Same as input data. Do not change or add tag"},
                "wingspan": {"type":"string", "description":"The wingpspan of the bird in question if sources dispute existing information or is null"},
                "size": {"type": "string", "description": "The size of the bird if sources dispute existing information or is null"},
                "identifying_marks": {"type": "string", "description": "The identifying descriptors of the bird if sources dispute existing information or is null"},
                "range": {"type": "string", "description": "The range of the bird if sources dispute existing information or is null"},
                "description": {"type": "string", "description": "Same as input data. Do not change or add tag"},
                "mating_season": {"type": "string", "description": "The mating season and mating ranges of the bird if sources dispute existing information or is null"},
            },
        },
        contents={"highlights":True}
    )

    # Turns output into an ordered list
    exa_result = results.output.content if results.output else None

    if exa_result:
        rarity = exa_result["rarity"]
        common_name = exa_result["common_name"]
        species = exa_result["species"]
        callUrl = None
        wingspan = exa_result["wingspan"]
        size = exa_result["size"]
        identifying_marks = exa_result["identifying_marks"]
        range_ = exa_result["range"]
        description = exa_result["description"]
        photographUrl = None
        mating_season = exa_result["mating_season"]

    finished_bird = [rarity, common_name, species,callUrl,wingspan,size,identifying_marks,range_,description,photographUrl,mating_season]

    return finished_bird






def write_to_file(scraped_csv_path = "data/scraped_birds.csv", processed_csv_path = "data/processed_birds.csv"):
    # creating the clients
    gemini_client = genai.Client(api_key=GEMINI_KEY)
    exa_client = Exa(EXA_KEY)

    # The input csv path. Where we read the bird names from
    scraped_csv_path = Path(scraped_csv_path)
    scraped_csv_path.parent.mkdir(parents=True, exist_ok=True)

    # The output csv path. Where we write the full bird data to
    processed_csv_path = Path(scraped_csv_path)
    processed_csv_path.parent.mkdir(parents=True, exist_ok=True)

    # Checking if the file exists
    file_exists = Path(processed_csv_path).exists()

    with (
        scraped_csv_path.open(
            "r",
            encoding="utf-8-sig",
            newline="",
        ) as scraped_file,
        processed_csv_path.open(
            "a",
            encoding="utf-8",
            newline = "",
        ) as processed_file
    ):
        try:
            reader = csv.reader(scraped_file)
            writer = csv.writer(processed_file)

            if not file_exists:
                writer.writerow("rarityID","commonName","species","callUrl","wingspan","size","identiftingMarks","range","description","photographUrl","matingSeason")

            for row in reader:
                prompt = f"{row}"

                parsed_bird = parse_bird_info(gemini_client, prompt)
                finished_bird = exa_lookup_and_format(exa_client,parsed_bird)
                

                writer.writerow(
                    finished_bird[0],
                    finished_bird[1],
                    finished_bird[2],
                    finished_bird[3],
                    finished_bird[4],
                    finished_bird[5],
                    finished_bird[6],
                    finished_bird[7],
                    finished_bird[8],
                    finished_bird[9],
                    finished_bird[10],
                )

                scraped_file.flush()

        finally:
            gemini_client.close()