-- MySQL Script generated by MySQL Workbench
-- Tue Jul 21 17:09:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Ayush Baruah && Joseph Eidel

SET FOREIGN_KEY_CHECKS = 0;
SET AUTOCOMMIT = 0;

-- -----------------------------------------------------
-- Table `Rarities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rarities`;

CREATE TABLE IF NOT EXISTS `Rarities` (
`rarityID` VARCHAR(45) NOT NULL,
PRIMARY KEY (`rarityID`),
UNIQUE INDEX `rarityID_UNIQUE` (`rarityID` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Birds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Birds`;

CREATE TABLE IF NOT EXISTS `Birds` (
`birdID` INT NOT NULL AUTO_INCREMENT,
`rarityID` VARCHAR(100) NOT NULL,
`commonName` VARCHAR(500) NOT NULL,
`species` VARCHAR(500) NOT NULL,
`wingspan` VARCHAR(500) NOT NULL,
`size` VARCHAR(500) NOT NULL,
`identifyingMarks` TEXT NOT NULL,
`range` TEXT NOT NULL,
`description` TEXT NOT NULL,
`matingSeason` TEXT NOT NULL,
PRIMARY KEY (`birdID`),
UNIQUE INDEX `species_UNIQUE` (`species` ASC) VISIBLE,
INDEX `fk_Birds_Rarities1_idx` (`rarityID` ASC) VISIBLE,
CONSTRAINT `fk_Birds_Rarities1`
  FOREIGN KEY (`rarityID`)
  REFERENCES `Rarities` (`rarityID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BirdPhotos`
-- One bird can have multiple photo candidates; isPrimary
-- marks the one shown by default
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BirdPhotos`;

CREATE TABLE IF NOT EXISTS `BirdPhotos` (
  `photoID` INT NOT NULL AUTO_INCREMENT,
  `birdID` INT NOT NULL,
  `photographUrl` TEXT NOT NULL,
  `license` TEXT NULL,
  `artist` TEXT NULL,
  PRIMARY KEY (`photoID`),
  INDEX `fk_BirdPhotos_Birds1_idx` (`birdID` ASC) VISIBLE,
  CONSTRAINT `fk_BirdPhotos_Birds1`
    FOREIGN KEY (`birdID`)
    REFERENCES `Birds` (`birdID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BirdCalls`
-- Same one-to-many shape as BirdPhotos, for audio
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BirdCalls`;

CREATE TABLE IF NOT EXISTS `BirdCalls` (
`callID` INT NOT NULL AUTO_INCREMENT,
`birdID` INT NOT NULL,
`callUrl` VARCHAR(1000) NOT NULL,
`license` VARCHAR(255) NULL,
`recordist` VARCHAR(500) NULL,
PRIMARY KEY (`callID`),
INDEX `fk_BirdCalls_Birds1_idx` (`birdID` ASC) VISIBLE,
CONSTRAINT `fk_BirdCalls_Birds1`
  FOREIGN KEY (`birdID`)
  REFERENCES `Birds` (`birdID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Nests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nests`;

CREATE TABLE IF NOT EXISTS `Nests` (
`nestID` INT NOT NULL AUTO_INCREMENT,
`type` VARCHAR(45) NOT NULL,
`location` VARCHAR(45) NOT NULL,
PRIMARY KEY (`nestID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Birders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Birders`;

CREATE TABLE IF NOT EXISTS `Birders` (
`birderID` INT NOT NULL AUTO_INCREMENT,
`birderName` VARCHAR(45) NOT NULL,
`points` INT NULL,
PRIMARY KEY (`birderID`),
UNIQUE INDEX `birderID_UNIQUE` (`birderID` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sightings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sightings`;

CREATE TABLE IF NOT EXISTS `Sightings` (
`sightingID` INT NOT NULL AUTO_INCREMENT,
`birderID` INT NOT NULL,
`birdID` INT NOT NULL,
`birdCount` INT NULL,
`gpsLocation` POINT NULL,
`time` DATETIME NULL,
PRIMARY KEY (`sightingID`),
INDEX `fk_Sightings_Birds1_idx` (`birdID` ASC) VISIBLE,
INDEX `fk_Sightings_Birders1_idx` (`birderID` ASC) VISIBLE,
CONSTRAINT `fk_Sightings_Birds1`
  FOREIGN KEY (`birdID`)
  REFERENCES `Birds` (`birdID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
CONSTRAINT `fk_Sightings_Birders1`
  FOREIGN KEY (`birderID`)
  REFERENCES `Birders` (`birderID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BirdsNests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BirdsNests`;

CREATE TABLE IF NOT EXISTS `BirdsNests` (
`birdID` INT NOT NULL,
`nestID` INT NOT NULL,
PRIMARY KEY (`birdID`, `nestID`),
INDEX `fk_BirdsNests_Birds_idx` (`birdID` ASC) VISIBLE,
INDEX `fk_BirdsNests_Nests1_idx` (`nestID` ASC) VISIBLE,
CONSTRAINT `fk_BirdsNests_Birds`
  FOREIGN KEY (`birdID`)
  REFERENCES `Birds` (`birdID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
CONSTRAINT `fk_BirdsNests_Nests1`
  FOREIGN KEY (`nestID`)
  REFERENCES `Nests` (`nestID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Rewards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rewards`;

CREATE TABLE IF NOT EXISTS `Rewards` (
`rewardID` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(45) NOT NULL,
`description` VARCHAR(45) NOT NULL,
`threshold` INT NULL,
PRIMARY KEY (`rewardID`),
UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
UNIQUE INDEX `rewardID_UNIQUE` (`rewardID` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BirdersRewards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BirdersRewards`;

CREATE TABLE IF NOT EXISTS `BirdersRewards` (
`rewardID` INT NOT NULL,
`birderID` INT NOT NULL,
PRIMARY KEY (`birderID`, `rewardID`),
INDEX `fk_BirdersRewards_Rewards1_idx` (`rewardID` ASC) VISIBLE,
INDEX `fk_BirdersRewards_Birders1_idx` (`birderID` ASC) VISIBLE,
CONSTRAINT `fk_BirdersRewards_Rewards1`
  FOREIGN KEY (`rewardID`)
  REFERENCES `Rewards` (`rewardID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
CONSTRAINT `fk_BirdersRewards_Birders1`
  FOREIGN KEY (`birderID`)
  REFERENCES `Birders` (`birderID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;













-- -----------------------------------------------------
-- -----------------------------------------------------
-- VIEWS
-- -----------------------------------------------------
-- -----------------------------------------------------

-- -----------------------------------------------------
-- View: BirdTotals
-- -----------------------------------------------------
DROP VIEW IF EXISTS v_bird_totals;

CREATE VIEW v_bird_totals AS
SELECT
Birders.birderName,
Birds.commonName AS birdName,
SUM(birdCount) AS totalCount
FROM Sightings
LEFT JOIN `Birders` ON `Sightings`.`birderID` = `Birders`.`birderID`
LEFT JOIN `Birds` ON `Birds`.`birdID` = `Sightings`.`birdID`
GROUP BY birderName, birdName
ORDER BY birderName;













-- -----------------------------------------------------
-- -----------------------------------------------------
-- INSERT LINES
-- -----------------------------------------------------
-- -----------------------------------------------------
INSERT INTO Rarities (rarityID)
VALUES ('Common'),('Uncommon'),('Rare'),('Legendary');

INSERT INTO `BirdCalls`(`birdID`,`callUrl`)
VALUES
(1, 'https://baldeaglecallhere.com'),
(2, 'https://americanrobincallhere.com'),
(3, 'https://bluejaycallhere.com'),
(4, 'https://northerncardinalcallhere.com'),
(5, 'https://red-tailedhawkcallhere.com'),
(6, 'https://greatblueheroncallhere.com'),
(7, 'https://americancrowcallhere.com'),
(8, 'https://commonravencallhere.com'),
(9, 'https://mourningdovecallhere.com');

INSERT INTO Nests (type, location)
VALUES
('Scrape', 'Tree'),
('Scrape', 'Cliff'),
('Scrape', 'Brush'),
('Scrape', 'Ground'),
('Scrape', 'Water'),
('Scrape', 'Man-Made Surface'),

('Platform', 'Tree'),
('Platform', 'Cliff'),
('Platform', 'Brush'),
('Platform', 'Ground'),
('Platform', 'Water'),
('Platform', 'Man-Made Surface'),

('Cup', 'Tree'),
('Cup', 'Cliff'),
('Cup', 'Brush'),
('Cup', 'Ground'),
('Cup', 'Water'),
('Cup', 'Man-Made Surface'),

('Domed', 'Tree'),
('Domed', 'Cliff'),
('Domed', 'Brush'),
('Domed', 'Ground'),
('Domed', 'Water'),
('Domed', 'Man-Made Surface'),

('Pendulous', 'Tree'),
('Pendulous', 'Cliff'),
('Pendulous', 'Brush'),
('Pendulous', 'Ground'),
('Pendulous', 'Water'),
('Pendulous', 'Man-Made Surface'),

('Pensile', 'Tree'),
('Pensile', 'Cliff'),
('Pensile', 'Brush'),
('Pensile', 'Ground'),
('Pensile', 'Water'),
('Pensile', 'Man-Made Surface'),

('Globular', 'Tree'),
('Globular', 'Cliff'),
('Globular', 'Brush'),
('Globular', 'Ground'),
('Globular', 'Water'),
('Globular', 'Man-Made Surface'),

('Cavity', 'Tree'),
('Cavity', 'Cliff'),
('Cavity', 'Brush'),
('Cavity', 'Ground'),
('Cavity', 'Water'),
('Cavity', 'Man-Made Surface'),

('Burrow', 'Tree'),
('Burrow', 'Cliff'),
('Burrow', 'Brush'),
('Burrow', 'Ground'),
('Burrow', 'Water'),
('Burrow', 'Man-Made Surface'),

('Mound', 'Tree'),
('Mound', 'Cliff'),
('Mound', 'Brush'),
('Mound', 'Ground'),
('Mound', 'Water'),
('Mound', 'Man-Made Surface');

INSERT INTO Birders (birderName, points)
VALUES
('Joseph Eidel', 13),('Ayush Baruah', 15),('Leonel Messi', 9),('David Attenborough', 61);

INSERT INTO Rewards (name, description, threshold)
VALUES 
('On My Way', 'Spotted your first 10 birds!',10),('Amatuer Birder', 'Spotted 25 birds!', 25), ('True Birder', 'Spotted 50 birds!', 50);

INSERT INTO Sightings (birderID, birdID, birdCount, gpsLocation, time)
VALUES
(1, 7, 4,NULL,NULL),
(1,9, 2, NULL, NULL),
(1, 4, 2, NULL, NULL),
(1, 7, 3, NULL, NULL),

(2, 7, 5, NULL, NULL),
(2, 2, 1, NULL, NULL),
(2, 5, 2, NULL, NULL),
(2, 1, 1, NULL, NULL),
(2, 8, 2, NULL, NULL),
(2, 6, 2, NULL, NULL),
(2, 9, 3, NULL, NULL),

(3, 8, 5, NULL, NULL),
(3, 3, 2, NULL, NULL),
(3, 9, 2, NULL, NULL),

(4, 1, 3, NULL, NULL),
(4, 2, 3, NULL, NULL),
(4, 3, 7, NULL, NULL),
(4, 4, 13, NULL, NULL),
(4, 7, 35, NULL, NULL);

INSERT INTO BirdersRewards (rewardID, birderID)
VALUES (1,1),(1,2),(1,4),(2,4),(3,4);

INSERT INTO BirdsNests
VALUES 
(1,7),
(1,8),

(2,14),

(3,14),

(4,15),

(5,7),
(5,8),

(6,7),

(7,7),

(8,8),

(9,7),
(9,10);

SET FOREIGN_KEY_CHECKS=1;
COMMIT;